"""Generate `filter-coeffs.js` for the JS inference demos from the canonical
Python preprocessing constants in `heed`.

This is the single source of truth for the deployment-side preprocessing
constants - the IIR filter sections + streaming initial conditions, the exact
Hann analysis window, the mel filterbank, and the scalar params (n_fft, hop,
…). Regenerating after any change to `heed/__init__.py` or `heed/audio.py`
keeps the browser / React-Native runtimes bit-identical to Python.

Run:
    python tools/gen_filter_coeffs.py            # writes both demo copies
    python tools/gen_filter_coeffs.py --stdout   # print to stdout instead

Everything is emitted at full float64 round-trip precision (Python ``repr``)
so the values JS parses are the same float64 bits Python used.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import scipy.signal
import torch

# Make the `heed` package importable when run as `python tools/gen_filter_coeffs.py`.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from heed import HOP_SAMPLES, N_FFT, N_MELS, SAMPLE_RATE, WIN_SAMPLES
from heed.audio import (
    _build_mel_filterbank,
    _hann,
    _hpf_coefficients,
    _notch_coefficients,
)

# Frame count for a 1-second window with center=True STFT (hop=160 → 101).
N_FRAMES = SAMPLE_RATE // HOP_SAMPLES + 1
N_BINS = N_FFT // 2 + 1


def _f(x: float) -> str:
    """Shortest round-trippable float64 literal (Python repr == JS double)."""
    return repr(float(x))


def _section_str(row: np.ndarray) -> str:
    # SOS row is [b0, b1, b2, a0(=1), a1, a2]; a0 is normalized away.
    b0, b1, b2, _a0, a1, a2 = (float(v) for v in row)
    return (
        f"    {{ b0: {_f(b0)}, b1: {_f(b1)}, b2: {_f(b2)}, "
        f"a1: {_f(a1)}, a2: {_f(a2)} }}"
    )


def _filter_block(name: str, sos: np.ndarray) -> str:
    """Emit one filter: SOS sections + per-section streaming zi (sosfilt_zi).

    `zi` is the steady-state initial condition; the streaming filter scales it
    by the first input sample of each stage on the first chunk (matches
    scipy.signal.sosfilt(sos, x, zi=sosfilt_zi*x[0]) and heed's
    StreamingHighpass).
    """
    zi = scipy.signal.sosfilt_zi(sos)  # (n_sections, 2)
    sections = ",\n".join(_section_str(r) for r in sos)
    zi_rows = ", ".join(f"[{_f(z[0])}, {_f(z[1])}]" for z in zi)
    return (
        f"  {name}: {{\n"
        f"    sections: [\n{sections}\n    ],\n"
        f"    zi: [{zi_rows}]\n"
        f"  }}"
    )


def _mel_sparse_str() -> str:
    """Sparse mel filterbank for n_fft=N_FFT: per mel bin, [(fft_bin, weight)…]."""
    fb = _build_mel_filterbank(n_mels=N_MELS, n_fft=N_FFT).numpy()  # (N_MELS, N_BINS)
    rows = []
    for b in range(N_MELS):
        pairs = [
            f"[{k},{_f(fb[b, k])}]" for k in range(fb.shape[1]) if fb[b, k] != 0.0
        ]
        rows.append("  [" + ", ".join(pairs) + "]")
    return ",\n".join(rows)


def _hann_str() -> str:
    """Exact torch.hann_window(WIN_SAMPLES) values (periodic - matches log_mel).

    Emitting the actual samples (rather than recomputing in JS) removes any
    risk of a periodic-vs-symmetric Hann mismatch between Python and JS.
    """
    w = _hann().numpy()  # length WIN_SAMPLES, periodic Hann (torch default)
    vals = ", ".join(_f(v) for v in w)
    return f"[{vals}]"


def generate() -> str:
    hpf = _hpf_coefficients(100.0, SAMPLE_RATE, 8)
    n50 = _notch_coefficients(50.0, 30.0, SAMPLE_RATE)
    n60 = _notch_coefficients(60.0, 30.0, SAMPLE_RATE)

    filters = ",\n".join(
        [
            _filter_block("hpf_100", hpf),
            _filter_block("notch_50", n50),
            _filter_block("notch_60", n60),
        ]
    )

    return f"""// Auto-generated by tools/gen_filter_coeffs.py - DO NOT EDIT BY HAND.
// Regenerate after any change to heed preprocessing:
//   python tools/gen_filter_coeffs.py
//
// Single source of truth for the deployment preprocessing constants. Mirrors
// heed/audio.py exactly (same SOS filter design, same torch Hann window,
// same mel filterbank), so the JS runtimes are bit-identical to Python.

// Scalar params shared by the preprocessor. nFft is a power of two so the FFT
// is a fast radix-2; winLength stays 25 ms (400 samples) and is zero-padded to
// nFft, exactly as torch.stft(n_fft={N_FFT}, win_length={WIN_SAMPLES}) does.
export const PARAMS = {{
  sampleRate: {SAMPLE_RATE},
  nFft: {N_FFT},
  winLength: {WIN_SAMPLES},
  hop: {HOP_SAMPLES},
  nMels: {N_MELS},
  nFrames: {N_FRAMES},
  nBins: {N_BINS},
}};

// IIR filters, applied in sequence as a CAUSAL streaming cascade with retained
// per-section state (see preprocessing.js BiquadCascade). Each `zi` is the
// steady-state initial condition (scipy.signal.sosfilt_zi), scaled by the
// stage's first input sample on the first chunk. Matches
// heed.audio.StreamingHighpass / highpass_filter bit-for-bit.
export const FILTERS = {{
{filters}
}};

// Exact torch.hann_window({WIN_SAMPLES}) (periodic). Placed centered inside the
// {N_FFT}-point FFT frame at offset (nFft - winLength) / 2.
export const HANN_WINDOW = {_hann_str()};

// Sparse mel filterbank for n_fft={N_FFT}: for each of {N_MELS} mel bins,
// [(fft_bin, weight), …] over the {N_BINS} unique FFT bins.
export const MEL_FB_SPARSE = [
{_mel_sparse_str()}
];
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print instead of writing files")
    args = ap.parse_args()

    js = generate()
    if args.stdout:
        print(js)
        return

    repo = Path(__file__).resolve().parent.parent  # …/code
    targets = [
        repo / "examples" / "inference_browser" / "filter-coeffs.js",
        repo / "examples" / "inference_react_native" / "src" / "filter-coeffs.js",
    ]
    for t in targets:
        t.write_text(js, encoding="utf-8")
        print(f"wrote {t}  ({len(js)} bytes)")
    print(
        f"\nparams: n_fft={N_FFT} win_length={WIN_SAMPLES} hop={HOP_SAMPLES} "
        f"n_mels={N_MELS} n_frames={N_FRAMES} n_bins={N_BINS}"
    )


if __name__ == "__main__":
    main()
